server:
  port: 18032
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

spring:
  config:
    import: optional:classpath:application-basic-pre.yml

logging:
  file:
    path: /data/logs/healthtrail-api-pre

healthtrail:
  file-base-dir: /home/healthtrail
  api-prefix: /pre-api
  demo-enabled: false
