
-- 健康系统 H2 测试环境业务表初始化脚本
--
-- 说明：
-- 1. 本脚本基于 PostgreSQL 最终表结构转换而来，目标是让 `test` 模式在 H2 内存库中也能完整承载健康业务。
-- 2. 所有业务表直接放在 H2 默认 `PUBLIC` schema，避免测试环境与正式 PostgreSQL 环境的对象落点再分叉。
-- 3. 这里只放建表和索引，示例数据单独放到 `health_test_data.sql`，方便后续维护和差异比对。

CREATE TABLE IF NOT EXISTS app_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile VARCHAR(16) NOT NULL,
    nickname VARCHAR(64) NOT NULL,
    avatar VARCHAR(255),
    password VARCHAR(128) NOT NULL,
    status SMALLINT DEFAULT 1 NOT NULL,
    last_login_ip VARCHAR(128),
    last_login_time TIMESTAMP,
    register_source VARCHAR(32) DEFAULT 'APP' NOT NULL,
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_app_user_mobile UNIQUE (mobile)
);

CREATE INDEX IF NOT EXISTS idx_app_user_status ON app_user (status);

CREATE TABLE IF NOT EXISTS family_member (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_code VARCHAR(32),
    owner_user_id BIGINT NOT NULL,
    member_name VARCHAR(64) NOT NULL,
    gender SMALLINT DEFAULT 0 NOT NULL,
    birthday DATE,
    relation_type VARCHAR(32) NOT NULL,
    height NUMERIC(5, 2),
    weight NUMERIC(5, 2),
    blood_type VARCHAR(16),
    allergy_history VARCHAR(500),
    chronic_history VARCHAR(500),
    remark VARCHAR(500),
    status SMALLINT DEFAULT 1 NOT NULL,
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_family_member_owner_user_id ON family_member (owner_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_family_member_code ON family_member (member_code);
CREATE INDEX IF NOT EXISTS idx_family_member_status ON family_member (status);

CREATE TABLE IF NOT EXISTS attachment (
    attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT,
    attachment_type VARCHAR(30) NOT NULL,
    storage_provider VARCHAR(30) DEFAULT 'LOCAL' NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255),
    file_size BIGINT,
    file_extension VARCHAR(20),
    content_type VARCHAR(100),
    status SMALLINT DEFAULT 1 NOT NULL,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_attachment_owner_user_id ON attachment (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_attachment_type ON attachment (attachment_type);
CREATE INDEX IF NOT EXISTS idx_attachment_status ON attachment (status);

CREATE TABLE IF NOT EXISTS drug_unit (
    unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_code VARCHAR(50) NOT NULL,
    unit_name VARCHAR(20) NOT NULL,
    unit_alias VARCHAR(200),
    precision_scale SMALLINT DEFAULT 0 NOT NULL,
    sort INT DEFAULT 0 NOT NULL,
    status SMALLINT DEFAULT 1 NOT NULL,
    icon_attachment_id BIGINT,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_drug_unit_code UNIQUE (unit_code, deleted),
    CONSTRAINT uk_drug_unit_name UNIQUE (unit_name, deleted)
);

CREATE INDEX IF NOT EXISTS idx_drug_unit_status ON drug_unit (status);
CREATE INDEX IF NOT EXISTS idx_drug_unit_sort ON drug_unit (sort);
CREATE INDEX IF NOT EXISTS idx_drug_unit_icon_attachment_id ON drug_unit (icon_attachment_id);

CREATE TABLE IF NOT EXISTS drug (
    drug_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_code VARCHAR(32),
    owner_user_id BIGINT NOT NULL,
    drug_name VARCHAR(100) NOT NULL,
    generic_name VARCHAR(100),
    brand_name VARCHAR(100),
    dosage_form VARCHAR(50),
    specification VARCHAR(100),
    indication VARCHAR(1000),
    usage_instruction VARCHAR(1000),
    adverse_reaction VARCHAR(1000),
    contraindication VARCHAR(1000),
    manufacturer VARCHAR(200),
    drug_type VARCHAR(20),
    source_drug_id BIGINT,
    stock_unit_id BIGINT,
    stock_unit VARCHAR(20),
    image_attachment_id BIGINT,
    stock_alert_threshold NUMERIC(10, 2),
    low_stock_notified SMALLINT DEFAULT 0 NOT NULL,
    low_stock_notify_time TIMESTAMP,
    status SMALLINT DEFAULT 1 NOT NULL,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_drug_owner_name UNIQUE (owner_user_id, drug_name)
);

CREATE INDEX IF NOT EXISTS idx_drug_owner_user_id ON drug (owner_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_drug_code ON drug (drug_code);
CREATE INDEX IF NOT EXISTS idx_drug_type ON drug (drug_type);
CREATE INDEX IF NOT EXISTS idx_drug_status ON drug (status);
CREATE INDEX IF NOT EXISTS idx_drug_stock_unit_id ON drug (stock_unit_id);
CREATE INDEX IF NOT EXISTS idx_drug_image_attachment_id ON drug (image_attachment_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_drug_owner_source ON drug (owner_user_id, source_drug_id);
CREATE INDEX IF NOT EXISTS idx_drug_stock_alert ON drug (owner_user_id, low_stock_notified, stock_alert_threshold);

CREATE TABLE IF NOT EXISTS drug_stock_batch (
    batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    drug_id BIGINT NOT NULL,
    batch_no VARCHAR(50),
    expire_date DATE,
    is_default_batch SMALLINT DEFAULT 0 NOT NULL,
    stock_quantity NUMERIC(10, 2) NOT NULL,
    near_expire_notified SMALLINT DEFAULT 0 NOT NULL,
    near_expire_notify_time TIMESTAMP,
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_drug_stock_batch_owner_user_id ON drug_stock_batch (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_drug_stock_batch_drug_id ON drug_stock_batch (drug_id);
CREATE INDEX IF NOT EXISTS idx_drug_stock_batch_expire_date ON drug_stock_batch (expire_date);
CREATE INDEX IF NOT EXISTS idx_drug_stock_batch_batch_no ON drug_stock_batch (batch_no);
CREATE INDEX IF NOT EXISTS idx_drug_stock_batch_default_batch ON drug_stock_batch (is_default_batch);

CREATE TABLE IF NOT EXISTS medication_plan (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code VARCHAR(32),
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    drug_id BIGINT,
    custom_drug_name VARCHAR(100),
    start_date DATE NOT NULL,
    end_date DATE,
    reminder_times_json VARCHAR(500) NOT NULL,
    meal_timing VARCHAR(30) DEFAULT 'NO_LIMIT' NOT NULL,
    dose_amount NUMERIC(10, 2),
    dose_unit VARCHAR(20),
    frequency_type VARCHAR(30) DEFAULT 'DAILY' NOT NULL,
    weekly_days_json VARCHAR(100),
    interval_hours INT,
    interval_days INT,
    dose_rule VARCHAR(1000),
    remark VARCHAR(500),
    status SMALLINT DEFAULT 1 NOT NULL,
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_medication_plan_owner_user_id ON medication_plan (owner_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_medication_plan_code ON medication_plan (plan_code);
CREATE INDEX IF NOT EXISTS idx_medication_plan_member_id ON medication_plan (member_id);
CREATE INDEX IF NOT EXISTS idx_medication_plan_frequency_type ON medication_plan (frequency_type);
CREATE INDEX IF NOT EXISTS idx_medication_plan_status ON medication_plan (status);

CREATE TABLE IF NOT EXISTS medication_reminder (
    reminder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    reminder_date DATE NOT NULL,
    scheduled_time TIMESTAMP NOT NULL,
    drug_name_snapshot VARCHAR(100) NOT NULL,
    dose_amount NUMERIC(10, 2),
    dose_unit VARCHAR(20),
    meal_timing VARCHAR(30),
    reminder_status SMALLINT DEFAULT 0 NOT NULL,
    notify_status SMALLINT DEFAULT 0 NOT NULL,
    notify_time TIMESTAMP,
    notify_fail_reason VARCHAR(255),
    notify_retry_count INT DEFAULT 0 NOT NULL,
    feedback_time TIMESTAMP,
    skip_reason VARCHAR(255),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_medication_reminder_owner_user_id ON medication_reminder (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_medication_reminder_plan_id ON medication_reminder (plan_id);
CREATE INDEX IF NOT EXISTS idx_medication_reminder_plan_time ON medication_reminder (plan_id, scheduled_time);
CREATE INDEX IF NOT EXISTS idx_medication_reminder_member_id ON medication_reminder (member_id);
CREATE INDEX IF NOT EXISTS idx_medication_reminder_scheduled_time ON medication_reminder (scheduled_time);
CREATE INDEX IF NOT EXISTS idx_medication_reminder_status ON medication_reminder (reminder_status);
CREATE INDEX IF NOT EXISTS idx_medication_reminder_notify_status ON medication_reminder (notify_status);

CREATE TABLE IF NOT EXISTS drug_stock_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    drug_id BIGINT NOT NULL,
    change_type VARCHAR(30) NOT NULL,
    before_quantity NUMERIC(10, 2),
    change_quantity NUMERIC(10, 2),
    after_quantity NUMERIC(10, 2),
    stock_unit_snapshot VARCHAR(20),
    alert_threshold_snapshot NUMERIC(10, 2),
    related_plan_id BIGINT,
    related_reminder_id BIGINT,
    related_temp_medication_id BIGINT,
    operation_remark VARCHAR(255),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_drug_stock_log_owner_user_id ON drug_stock_log (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_drug_stock_log_drug_id ON drug_stock_log (drug_id);
CREATE INDEX IF NOT EXISTS idx_drug_stock_log_change_type ON drug_stock_log (change_type);
CREATE INDEX IF NOT EXISTS idx_drug_stock_log_reminder_id ON drug_stock_log (related_reminder_id);
CREATE INDEX IF NOT EXISTS idx_drug_stock_log_temp_medication_id ON drug_stock_log (related_temp_medication_id);

CREATE TABLE IF NOT EXISTS drug_temporary_medication_record (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT,
    drug_id BIGINT NOT NULL,
    used_quantity NUMERIC(10, 2) NOT NULL,
    stock_unit_snapshot VARCHAR(20),
    use_time TIMESTAMP NOT NULL,
    symptom VARCHAR(100),
    remark VARCHAR(255),
    deducted_quantity NUMERIC(10, 2) NOT NULL,
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_drug_temp_medication_owner_user_id ON drug_temporary_medication_record (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_drug_temp_medication_member_id ON drug_temporary_medication_record (member_id);
CREATE INDEX IF NOT EXISTS idx_drug_temp_medication_drug_id ON drug_temporary_medication_record (drug_id);
CREATE INDEX IF NOT EXISTS idx_drug_temp_medication_use_time ON drug_temporary_medication_record (use_time);

CREATE TABLE IF NOT EXISTS report (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    report_name VARCHAR(100) NOT NULL,
    report_type VARCHAR(50),
    recognized_report_type VARCHAR(50),
    hospital_name VARCHAR(100),
    report_date DATE,
    file_url VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    file_size BIGINT,
    file_extension VARCHAR(20),
    parse_status SMALLINT DEFAULT 0 NOT NULL,
    ai_parse_cached SMALLINT DEFAULT 0 NOT NULL,
    ocr_status SMALLINT DEFAULT 0 NOT NULL,
    ocr_text_snapshot VARCHAR(2000),
    ocr_time TIMESTAMP,
    ai_summary_status SMALLINT DEFAULT 0 NOT NULL,
    ai_summary_content VARCHAR(2000),
    ai_summary_time TIMESTAMP,
    analysis_summary VARCHAR(1000),
    result_interpretation VARCHAR(2000),
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_report_owner_user_id ON report (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_report_member_id ON report (member_id);
CREATE INDEX IF NOT EXISTS idx_report_report_date ON report (report_date);
CREATE INDEX IF NOT EXISTS idx_report_parse_status ON report (parse_status);

CREATE TABLE IF NOT EXISTS report_item (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    item_code VARCHAR(64),
    standard_item_code VARCHAR(64),
    item_name VARCHAR(100) NOT NULL,
    result_value VARCHAR(100) NOT NULL,
    result_unit VARCHAR(50),
    reference_min NUMERIC(10, 4),
    reference_max NUMERIC(10, 4),
    reference_text VARCHAR(100),
    item_interpretation VARCHAR(300),
    abnormal_flag SMALLINT DEFAULT 0 NOT NULL,
    sort INT DEFAULT 0 NOT NULL,
    remark VARCHAR(255),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_report_item_report_id ON report_item (report_id);
CREATE INDEX IF NOT EXISTS idx_report_item_owner_user_id ON report_item (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_report_item_standard_item_code ON report_item (standard_item_code);
CREATE INDEX IF NOT EXISTS idx_report_item_abnormal_flag ON report_item (abnormal_flag);

CREATE TABLE IF NOT EXISTS health_problem (
    problem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    problem_name VARCHAR(100) NOT NULL,
    problem_type VARCHAR(50) NOT NULL,
    problem_status SMALLINT DEFAULT 1 NOT NULL,
    risk_level SMALLINT DEFAULT 1 NOT NULL,
    standard_item_code VARCHAR(64),
    first_found_date DATE,
    last_follow_date DATE,
    summary VARCHAR(1000),
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_health_problem_member_id ON health_problem (member_id);
CREATE INDEX IF NOT EXISTS idx_health_problem_standard_code ON health_problem (standard_item_code);

CREATE TABLE IF NOT EXISTS health_problem_evidence (
    evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    evidence_type VARCHAR(50) NOT NULL,
    report_id BIGINT,
    report_item_id BIGINT,
    evidence_title VARCHAR(100),
    evidence_summary VARCHAR(1000),
    evidence_date DATE,
    confidence_level SMALLINT DEFAULT 0 NOT NULL,
    confirm_status SMALLINT DEFAULT 0 NOT NULL,
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_health_problem_evidence_problem_id ON health_problem_evidence (problem_id);
CREATE INDEX IF NOT EXISTS idx_health_problem_evidence_report_id ON health_problem_evidence (report_id);
CREATE INDEX IF NOT EXISTS idx_health_problem_evidence_report_item_id ON health_problem_evidence (report_item_id);

CREATE TABLE IF NOT EXISTS app_device (
    device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    device_code VARCHAR(64) NOT NULL,
    push_platform VARCHAR(20) NOT NULL,
    device_token VARCHAR(255) NOT NULL,
    device_model VARCHAR(100),
    manufacturer VARCHAR(100),
    os_version VARCHAR(50),
    app_version VARCHAR(50),
    last_active_time TIMESTAMP,
    status SMALLINT DEFAULT 1 NOT NULL,
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_app_device_code UNIQUE (device_code)
);

CREATE INDEX IF NOT EXISTS idx_app_device_owner_user_id ON app_device (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_app_device_status ON app_device (status);
CREATE INDEX IF NOT EXISTS idx_app_device_token ON app_device (device_token);

CREATE TABLE IF NOT EXISTS app_message (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT,
    member_name_snapshot VARCHAR(50),
    business_scene VARCHAR(40) NOT NULL,
    business_id BIGINT NOT NULL,
    message_title VARCHAR(100) NOT NULL,
    message_content VARCHAR(500),
    payload_json TEXT,
    dedup_key VARCHAR(100),
    read_status SMALLINT DEFAULT 0 NOT NULL,
    read_time TIMESTAMP,
    send_status SMALLINT DEFAULT 0 NOT NULL,
    send_time TIMESTAMP,
    send_channel VARCHAR(30),
    send_retry_count INT DEFAULT 0 NOT NULL,
    send_result_message VARCHAR(255),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_app_message_owner_dedup UNIQUE (owner_user_id, dedup_key)
);

CREATE INDEX IF NOT EXISTS idx_app_message_owner_user_id ON app_message (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_app_message_owner_read_status ON app_message (owner_user_id, read_status);
CREATE INDEX IF NOT EXISTS idx_app_message_business_scene ON app_message (business_scene);
CREATE INDEX IF NOT EXISTS idx_app_message_business_id ON app_message (business_id);

-- App Push 设备级派发审计表。
--
-- 这里必须直接并入 H2 基础测试 schema，而不能只依赖 PostgreSQL 增量脚本。
-- 原因是 API 集成测试启动时只会执行 H2 初始化 SQL；如果这张表缺失，
-- 低库存提醒在“模拟 Push 成功 -> 写设备级审计”这一步就会因为缺表抛异常，
-- 进而把本应成功的消息回写成发送失败，连带导致 lowStockNotified 无法置为 true。
CREATE TABLE IF NOT EXISTS app_push_delivery_log (
    delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT,
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT,
    business_scene VARCHAR(40) NOT NULL,
    business_id BIGINT,
    device_id BIGINT NOT NULL,
    device_code VARCHAR(64),
    push_platform VARCHAR(20),
    device_status_snapshot SMALLINT,
    device_token_masked VARCHAR(40),
    send_channel VARCHAR(30),
    send_status SMALLINT NOT NULL,
    failure_reason_category VARCHAR(30),
    failure_reason_message VARCHAR(255),
    vendor_code VARCHAR(50),
    vendor_message VARCHAR(255),
    retry_no INT DEFAULT 1 NOT NULL,
    send_time TIMESTAMP,
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_app_push_delivery_log_message_id ON app_push_delivery_log (message_id);
CREATE INDEX IF NOT EXISTS idx_app_push_delivery_log_owner_user_id ON app_push_delivery_log (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_app_push_delivery_log_device_id ON app_push_delivery_log (device_id);
CREATE INDEX IF NOT EXISTS idx_app_push_delivery_log_business_scene ON app_push_delivery_log (business_scene);
CREATE INDEX IF NOT EXISTS idx_app_push_delivery_log_send_time ON app_push_delivery_log (send_time);
CREATE INDEX IF NOT EXISTS idx_app_push_delivery_log_send_status ON app_push_delivery_log (send_status);
CREATE INDEX IF NOT EXISTS idx_app_push_delivery_log_failure_reason_category
    ON app_push_delivery_log (failure_reason_category);
CREATE INDEX IF NOT EXISTS idx_app_push_delivery_log_message_retry ON app_push_delivery_log (message_id, retry_no);

CREATE TABLE IF NOT EXISTS follow_up_task (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT,
    task_type VARCHAR(30) NOT NULL,
    source_id BIGINT NOT NULL,
    task_status SMALLINT DEFAULT 0 NOT NULL,
    read_status SMALLINT DEFAULT 0 NOT NULL,
    read_time TIMESTAMP,
    delayed_until TIMESTAMP,
    complete_time TIMESTAMP,
    action_remark VARCHAR(255),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_follow_up_task_owner_source
    ON follow_up_task (owner_user_id, task_type, source_id);
CREATE INDEX IF NOT EXISTS idx_follow_up_task_owner_user_id ON follow_up_task (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_follow_up_task_member_id ON follow_up_task (member_id);
CREATE INDEX IF NOT EXISTS idx_follow_up_task_status ON follow_up_task (task_status);
CREATE INDEX IF NOT EXISTS idx_follow_up_task_owner_read_status ON follow_up_task (owner_user_id, read_status);
CREATE INDEX IF NOT EXISTS idx_follow_up_task_delayed_until ON follow_up_task (delayed_until);

CREATE TABLE IF NOT EXISTS follow_up_task_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT,
    task_type VARCHAR(30) NOT NULL,
    source_id BIGINT NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    before_status SMALLINT,
    after_status SMALLINT,
    action_remark VARCHAR(255),
    delayed_until_snapshot TIMESTAMP,
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_follow_up_task_log_task_id ON follow_up_task_log (task_id);
CREATE INDEX IF NOT EXISTS idx_follow_up_task_log_owner_user_id ON follow_up_task_log (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_follow_up_task_log_source ON follow_up_task_log (task_type, source_id);
CREATE INDEX IF NOT EXISTS idx_follow_up_task_log_create_time ON follow_up_task_log (create_time);

CREATE TABLE IF NOT EXISTS operation_task (
    operation_task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT,
    task_title VARCHAR(100) NOT NULL,
    task_content VARCHAR(500),
    action_text VARCHAR(50) DEFAULT '去查看' NOT NULL,
    risk_level VARCHAR(20) DEFAULT 'MEDIUM' NOT NULL,
    priority_weight INT DEFAULT 0 NOT NULL,
    target_page_code VARCHAR(50),
    target_page_name VARCHAR(50),
    target_biz_id BIGINT,
    target_biz_type VARCHAR(30),
    target_tab_code VARCHAR(30),
    target_anchor_code VARCHAR(50),
    target_anchor_name VARCHAR(50),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status SMALLINT DEFAULT 1 NOT NULL,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_operation_task_owner_user_id ON operation_task (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_operation_task_member_id ON operation_task (member_id);
CREATE INDEX IF NOT EXISTS idx_operation_task_status ON operation_task (status);
CREATE INDEX IF NOT EXISTS idx_operation_task_risk_level ON operation_task (risk_level);
CREATE INDEX IF NOT EXISTS idx_operation_task_start_time ON operation_task (start_time);
CREATE INDEX IF NOT EXISTS idx_operation_task_end_time ON operation_task (end_time);
CREATE INDEX IF NOT EXISTS idx_operation_task_owner_status_time
    ON operation_task (owner_user_id, status, start_time, end_time);

CREATE TABLE IF NOT EXISTS family_member_share (
    share_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    collaborator_user_id BIGINT NOT NULL,
    invite_id BIGINT,
    share_role VARCHAR(20) NOT NULL,
    share_status SMALLINT DEFAULT 1 NOT NULL,
    accepted_time TIMESTAMP,
    remark VARCHAR(255),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_family_member_share_member_collaborator
    ON family_member_share (member_id, collaborator_user_id, deleted);
CREATE INDEX IF NOT EXISTS idx_family_member_share_owner_user_id ON family_member_share (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_family_member_share_collaborator_user_id ON family_member_share (collaborator_user_id);
CREATE INDEX IF NOT EXISTS idx_family_member_share_status ON family_member_share (share_status);

CREATE TABLE IF NOT EXISTS family_share_invite (
    invite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    invite_code VARCHAR(32) NOT NULL,
    invitee_user_id BIGINT,
    share_role VARCHAR(20) NOT NULL,
    invite_status SMALLINT DEFAULT 0 NOT NULL,
    expire_time TIMESTAMP NOT NULL,
    accepted_time TIMESTAMP,
    remark VARCHAR(255),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_family_share_invite_invite_code UNIQUE (invite_code, deleted)
);

CREATE INDEX IF NOT EXISTS idx_family_share_invite_member_id ON family_share_invite (member_id);
CREATE INDEX IF NOT EXISTS idx_family_share_invite_owner_user_id ON family_share_invite (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_family_share_invite_status ON family_share_invite (invite_status);
CREATE INDEX IF NOT EXISTS idx_family_share_invite_expire_time ON family_share_invite (expire_time);

CREATE TABLE IF NOT EXISTS indicator_template (
    template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type VARCHAR(50),
    item_code VARCHAR(64),
    item_name VARCHAR(100) NOT NULL,
    result_unit VARCHAR(50),
    reference_min NUMERIC(10, 4),
    reference_max NUMERIC(10, 4),
    reference_text VARCHAR(100),
    suggestion_template VARCHAR(1000),
    sort INT DEFAULT 0 NOT NULL,
    status SMALLINT DEFAULT 1 NOT NULL,
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_indicator_template_report_type ON indicator_template (report_type);
CREATE INDEX IF NOT EXISTS idx_indicator_template_item_code ON indicator_template (item_code);
CREATE INDEX IF NOT EXISTS idx_indicator_template_item_name ON indicator_template (item_name);
CREATE INDEX IF NOT EXISTS idx_indicator_template_status ON indicator_template (status);

CREATE TABLE IF NOT EXISTS health_chronic_disease_type (
    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disease_code VARCHAR(64) NOT NULL,
    disease_name VARCHAR(100) NOT NULL,
    disease_category VARCHAR(50),
    focus_indicator_codes_json VARCHAR(1000),
    focus_indicator_keywords_json VARCHAR(1000),
    target_summary VARCHAR(500),
    follow_up_suggestion VARCHAR(1000),
    sort INT DEFAULT 0 NOT NULL,
    status SMALLINT DEFAULT 1 NOT NULL,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL,
    CONSTRAINT uk_health_chronic_disease_type_code UNIQUE (disease_code)
);

CREATE INDEX IF NOT EXISTS idx_health_chronic_disease_type_status ON health_chronic_disease_type (status);
CREATE INDEX IF NOT EXISTS idx_health_chronic_disease_type_sort ON health_chronic_disease_type (sort);

CREATE TABLE IF NOT EXISTS health_chronic_disease_profile (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    disease_code VARCHAR(64) NOT NULL,
    disease_name_snapshot VARCHAR(100) NOT NULL,
    profile_status SMALLINT DEFAULT 1 NOT NULL,
    risk_level VARCHAR(20) DEFAULT 'LOW' NOT NULL,
    diagnosed_date DATE,
    target_summary VARCHAR(500),
    current_summary VARCHAR(1000),
    last_review_date DATE,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_health_chronic_profile_member_disease
    ON health_chronic_disease_profile (member_id, disease_code, deleted);
CREATE INDEX IF NOT EXISTS idx_health_chronic_profile_owner_user_id ON health_chronic_disease_profile (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_health_chronic_profile_member_id ON health_chronic_disease_profile (member_id);
CREATE INDEX IF NOT EXISTS idx_health_chronic_profile_status ON health_chronic_disease_profile (profile_status);
CREATE INDEX IF NOT EXISTS idx_health_chronic_profile_risk ON health_chronic_disease_profile (risk_level);

CREATE TABLE IF NOT EXISTS health_chronic_indicator_target (
    target_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    indicator_code VARCHAR(100) NOT NULL,
    indicator_name VARCHAR(100),
    target_min NUMERIC(18, 4),
    target_max NUMERIC(18, 4),
    target_text VARCHAR(200),
    result_unit VARCHAR(50),
    status SMALLINT DEFAULT 1 NOT NULL,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL,
    CONSTRAINT ck_health_chronic_indicator_target_range
        CHECK (target_min IS NULL OR target_max IS NULL OR target_min <= target_max)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_health_chronic_indicator_target_profile_code
    ON health_chronic_indicator_target (profile_id, indicator_code, deleted);
CREATE INDEX IF NOT EXISTS idx_health_chronic_indicator_target_owner
    ON health_chronic_indicator_target (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_health_chronic_indicator_target_member
    ON health_chronic_indicator_target (member_id);
CREATE INDEX IF NOT EXISTS idx_health_chronic_indicator_target_profile_status
    ON health_chronic_indicator_target (profile_id, status);

CREATE TABLE IF NOT EXISTS member_feature (
    member_feature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_code VARCHAR(64) NOT NULL,
    feature_name VARCHAR(100) NOT NULL,
    feature_type VARCHAR(20) NOT NULL,
    quota_period_type VARCHAR(20),
    free_enabled SMALLINT DEFAULT 0 NOT NULL,
    free_limit_value INT,
    feature_sort INT DEFAULT 0 NOT NULL,
    status SMALLINT DEFAULT 1 NOT NULL,
    is_builtin SMALLINT DEFAULT 1 NOT NULL,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_member_feature_code ON member_feature (feature_code);

CREATE TABLE IF NOT EXISTS member_level (
    member_level_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_code VARCHAR(32) NOT NULL,
    level_name VARCHAR(100) NOT NULL,
    level_sort INT DEFAULT 0 NOT NULL,
    price NUMERIC(10, 2) DEFAULT 0 NOT NULL,
    duration_days INT,
    benefit_desc VARCHAR(1000),
    status SMALLINT DEFAULT 1 NOT NULL,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_member_level_code ON member_level (level_code);

CREATE TABLE IF NOT EXISTS member_level_feature (
    member_level_feature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_level_id BIGINT NOT NULL,
    member_feature_id BIGINT NOT NULL,
    enabled SMALLINT DEFAULT 0 NOT NULL,
    limit_value INT,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_member_level_feature_level_feature
    ON member_level_feature (member_level_id, member_feature_id, deleted);

CREATE TABLE IF NOT EXISTS user_member (
    user_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    member_level_id BIGINT NOT NULL,
    effective_start_time TIMESTAMP NOT NULL,
    effective_end_time TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_id BIGINT,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_member_user_id ON user_member (user_id, deleted);

CREATE TABLE IF NOT EXISTS member_redeem_code (
    member_redeem_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no VARCHAR(64) NOT NULL,
    redeem_code VARCHAR(64) NOT NULL,
    member_level_id BIGINT NOT NULL,
    level_code_snapshot VARCHAR(32) NOT NULL,
    level_name_snapshot VARCHAR(100) NOT NULL,
    price_snapshot NUMERIC(10, 2) DEFAULT 0 NOT NULL,
    duration_days_snapshot INT,
    code_status VARCHAR(20) NOT NULL,
    redeemed_user_id BIGINT,
    redeemed_time TIMESTAMP,
    expire_time TIMESTAMP,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_member_redeem_code_code ON member_redeem_code (redeem_code);

CREATE TABLE IF NOT EXISTS member_feature_quota_usage (
    member_feature_quota_usage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    member_feature_id BIGINT NOT NULL,
    feature_code_snapshot VARCHAR(64) NOT NULL,
    quota_period_type VARCHAR(20) NOT NULL,
    period_key VARCHAR(16) NOT NULL,
    used_count INT DEFAULT 0 NOT NULL,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_member_feature_quota_usage_user_feature_period
    ON member_feature_quota_usage (user_id, member_feature_id, period_key, deleted);

CREATE TABLE IF NOT EXISTS member_gate (
    member_gate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gate_code VARCHAR(64) NOT NULL,
    gate_name VARCHAR(100) NOT NULL,
    gate_scope VARCHAR(30) NOT NULL,
    biz_module VARCHAR(50) NOT NULL,
    terminal_type VARCHAR(20) NOT NULL,
    default_policy_type VARCHAR(20) DEFAULT 'ALLOW' NOT NULL,
    status SMALLINT DEFAULT 1 NOT NULL,
    is_builtin SMALLINT DEFAULT 1 NOT NULL,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_member_gate_code ON member_gate (gate_code);
CREATE INDEX IF NOT EXISTS idx_member_gate_scope ON member_gate (gate_scope);
CREATE INDEX IF NOT EXISTS idx_member_gate_biz_module ON member_gate (biz_module);
CREATE INDEX IF NOT EXISTS idx_member_gate_terminal_type ON member_gate (terminal_type);
CREATE INDEX IF NOT EXISTS idx_member_gate_status ON member_gate (status);

CREATE TABLE IF NOT EXISTS member_gate_rule (
    member_gate_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_gate_id BIGINT NOT NULL,
    policy_type VARCHAR(20) NOT NULL,
    feature_code VARCHAR(64),
    allowed_level_codes_json CLOB,
    deny_client_mode VARCHAR(20) DEFAULT 'DIALOG' NOT NULL,
    deny_title VARCHAR(100),
    deny_message VARCHAR(500),
    guide_member_page SMALLINT DEFAULT 1 NOT NULL,
    priority INT DEFAULT 0 NOT NULL,
    status SMALLINT DEFAULT 1 NOT NULL,
    version_no INT DEFAULT 1 NOT NULL,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_member_gate_rule_gate_id ON member_gate_rule (member_gate_id, deleted);
CREATE INDEX IF NOT EXISTS idx_member_gate_rule_policy_type ON member_gate_rule (policy_type);
CREATE INDEX IF NOT EXISTS idx_member_gate_rule_feature_code ON member_gate_rule (feature_code);
CREATE INDEX IF NOT EXISTS idx_member_gate_rule_status ON member_gate_rule (status);

CREATE TABLE IF NOT EXISTS user_member_order (
    user_member_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    subscription_id BIGINT,
    user_id BIGINT NOT NULL,
    member_level_id BIGINT NOT NULL,
    order_type VARCHAR(20) NOT NULL,
    order_status VARCHAR(20) NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    order_amount NUMERIC(10, 2) DEFAULT 0 NOT NULL,
    pay_time TIMESTAMP,
    effective_start_time TIMESTAMP,
    effective_end_time TIMESTAMP,
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_member_order_order_no ON user_member_order (order_no);

CREATE TABLE IF NOT EXISTS user_member_subscription (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    member_level_id BIGINT NOT NULL,
    subscription_status VARCHAR(20) NOT NULL,
    auto_renew SMALLINT DEFAULT 0 NOT NULL,
    current_period_start_time TIMESTAMP,
    current_period_end_time TIMESTAMP,
    next_renew_time TIMESTAMP,
    last_renew_time TIMESTAMP,
    failed_renew_count INT DEFAULT 0 NOT NULL,
    cancel_time TIMESTAMP,
    cancel_reason VARCHAR(500),
    remark VARCHAR(500),
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_member_subscription_no ON user_member_subscription (subscription_no);
