server:
    port: 18001
    servlet:
        context-path: /
    tomcat:
        uri-encoding: UTF-8
        accept-count: 1000
        threads:
            max: 800
            min-spare: 100

spring:
    config:
        import: optional:classpath:application-basic-prod.yml

logging:
    file:
        path: /data/logs/healthtrail-admin-prod

springdoc:
    swagger-ui:
        enabled: true
        url: ${healthtrail.api-prefix}/v3/api-docs
        config-url: ${healthtrail.api-prefix}/v3/api-docs/swagger-config

healthtrail:
    file-base-dir: /home/healthtrail
    api-prefix: /prod-api
    demo-enabled: false
